### ISSUE TITLE
parameter "source" cannot be null

### ISSUE THREAD

**Issue by Maverickwoe** [CheeseJedi/HELLION.Explorer#1]
Hi
Tried loading a saved game and it crashed.
Maybe related to the fact I cannot load and join the game too... not sure.
If you want to debug this, here is the file

"parameter "source" cannot be null"

[ServerSave_2017-11-15-18-00-57.zip](https://github.com/CheeseJedi/HELLION.Explorer/files/1475822/ServerSave_2017-11-15-18-00-57.zip)

**Comment by CheeseJedi** [comment]
Thanks for reporting this. I'll check out the file you linked.

**Comment by CheeseJedi** [comment]
The save file you linked loaded without issue. I checked it in build 0.0.4.4 and the latest version I have and it seemed ok.

I suspect that the Data folder is not pointing to the correct place. HELLION Explorer, and the HELLION Dedicated Server both are heavily reliant on the files that reside in the Data folder, part of the DS installation. These include the CelestialBodies.json file which determines the orbital hierarchy, and placing asteroids and ships/modules will fail if this file is damaged or missing.

The Explorer has an option in the Tools menu to set the Data folder location - this opens a folder browser window and you should point it to wherever your dedicated server installation is, specifically at the Data folder. (This folder has a subfolder called collisions on the most recent DS builds).

If you are using a 3rd party game hoster (rather than a local DS installation) you may need to download the data folder, and it's contents, via a similar method you retrieved your .save file - perhaps FTP.

So long as the Data folder is correctly set, it should work. Let me know if this hasn't helped opening your save files.

Thanks for taking the time to report this and upload a sample .save file!

**Comment by CheeseJedi** [comment]
Oh, I forgot to add, the build I'm currently working on has improved detection of a bad Data folder path so these problems should be lessened.

**Comment by CheeseJedi** [comment]
Please re-try this with the new build.

Thanks.
